"""mvp_models

Revision ID: 8c051eb5b980
Revises: b1f898006b23
Create Date: 2026-05-06 21:25:12.326292

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c051eb5b980'
down_revision = 'b1f898006b23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###