"""initial_schema_from_data_models

Revision ID: a50e5d074d83
Revises: 
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a50e5d074d83'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('language_preference', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('subscription_plan', sa.String(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creator_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('secondary_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('location_country', sa.String(length=2), nullable=True),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('social_handles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('influence_score', sa.Float(), nullable=True),
    sa.Column('total_followers', sa.Integer(), nullable=True),
    sa.Column('avg_engagement_rate', sa.Float(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_creator_profiles_category'), 'creator_profiles', ['category'], unique=False)
    op.create_index(op.f('ix_creator_profiles_is_public'), 'creator_profiles', ['is_public'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('related_entity_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform_name', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('platform_user_id', sa.String(), nullable=False),
    sa.Column('platform_username', sa.String(), nullable=True),
    sa.Column('scopes_granted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_connections_is_active'), 'platform_connections', ['is_active'], unique=False)
    op.create_table('sme_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('payment_gateway_customer_id', sa.String(), nullable=True),
    sa.Column('monthly_budget_ngn', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_sme_profiles_industry'), 'sme_profiles', ['industry'], unique=False)
    op.create_table('audience_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform_connection_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('total_followers', sa.Integer(), nullable=True),
    sa.Column('new_followers_this_period', sa.Integer(), nullable=True),
    sa.Column('age_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gender_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_countries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_cities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creator_profiles.id'], ),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sme_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('objective', sa.String(), nullable=False),
    sa.Column('total_budget_ngn', sa.Numeric(), nullable=True),
    sa.Column('spent_budget_ngn', sa.Numeric(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('target_platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_influence_score', sa.Float(), nullable=True),
    sa.Column('min_followers', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sme_id'], ['sme_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('content_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('platform_connection_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('permalink', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('detected_language', sa.String(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creator_profiles.id'], ),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_external_id'), 'content_items', ['external_id'], unique=True)
    op.create_table('influence_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('data_window_days', sa.Integer(), nullable=True),
    sa.Column('platforms_included', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creator_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_collaborations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('negotiated_fee_ngn', sa.Numeric(), nullable=True),
    sa.Column('payment_gateway_reference', sa.String(), nullable=True),
    sa.Column('tracking_link', sa.String(), nullable=True),
    sa.Column('tracking_code', sa.String(), nullable=True),
    sa.Column('total_clicks', sa.Integer(), nullable=True),
    sa.Column('total_conversions', sa.Integer(), nullable=True),
    sa.Column('estimated_roi', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creator_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_collaborations_status'), 'campaign_collaborations', ['status'], unique=False)
    op.create_index(op.f('ix_campaign_collaborations_tracking_code'), 'campaign_collaborations', ['tracking_code'], unique=True)
    op.create_table('content_metric_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('likes', sa.BigInteger(), nullable=True),
    sa.Column('comments', sa.BigInteger(), nullable=True),
    sa.Column('shares', sa.BigInteger(), nullable=True),
    sa.Column('saves', sa.BigInteger(), nullable=True),
    sa.Column('reposts', sa.BigInteger(), nullable=True),
    sa.Column('watch_time_seconds', sa.Integer(), nullable=True),
    sa.Column('average_view_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('click_through_rate', sa.Float(), nullable=True),
    sa.Column('streams', sa.BigInteger(), nullable=True),
    sa.Column('playlist_adds', sa.BigInteger(), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('reach', sa.BigInteger(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_creator_briefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collaboration_id', sa.UUID(), nullable=False),
    sa.Column('deliverables', sa.String(), nullable=False),
    sa.Column('dos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('donts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('brand_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hashtags_required', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reference_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submission_deadline', sa.Date(), nullable=True),
    sa.Column('revision_limit', sa.Integer(), nullable=True),
    sa.Column('additional_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_id'], ['campaign_collaborations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collaboration_id')
    )
    op.create_table('conversion_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collaboration_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('tracking_code', sa.String(), nullable=False),
    sa.Column('revenue_ngn', sa.Numeric(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('ip_country', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('custom_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_id'], ['campaign_collaborations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversion_events_tracking_code'), 'conversion_events', ['tracking_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversion_events_tracking_code'), table_name='conversion_events')
    op.drop_table('conversion_events')
    op.drop_table('campaign_creator_briefs')
    op.drop_table('content_metric_snapshots')
    op.drop_index(op.f('ix_campaign_collaborations_tracking_code'), table_name='campaign_collaborations')
    op.drop_index(op.f('ix_campaign_collaborations_status'), table_name='campaign_collaborations')
    op.drop_table('campaign_collaborations')
    op.drop_table('influence_scores')
    op.drop_index(op.f('ix_content_items_external_id'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('audience_snapshots')
    op.drop_index(op.f('ix_sme_profiles_industry'), table_name='sme_profiles')
    op.drop_table('sme_profiles')
    op.drop_index(op.f('ix_platform_connections_is_active'), table_name='platform_connections')
    op.drop_table('platform_connections')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_creator_profiles_is_public'), table_name='creator_profiles')
    op.drop_index(op.f('ix_creator_profiles_category'), table_name='creator_profiles')
    op.drop_table('creator_profiles')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
