"""mvp_models

Revision ID: b1f898006b23
Revises: a50e5d074d83
Create Date: 2026-05-06 21:20:36.594509

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f898006b23'
down_revision = 'a50e5d074d83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collaboration_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_id'], ['campaign_collaborations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_collaboration_id'), 'messages', ['collaboration_id'], unique=False)
    op.add_column('users', sa.Column('is_merged', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('merged_into_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_is_merged'), 'users', ['is_merged'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['merged_into_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_is_merged'), table_name='users')
    op.drop_column('users', 'merged_into_id')
    op.drop_column('users', 'is_merged')
    op.drop_index(op.f('ix_messages_collaboration_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###